force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto__c/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <displayFormat>P-{0000}</displayFormat>
    <label>Código de Produto</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Produto__c/fields/DescricaoProduto__c.field-meta.xml
<CustomField>
    <fullName>DescricaoProduto__c</fullName>
    <label>Descrição de Produto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Produto__c/fields/PrecoProduto__c.field-meta.xml
<CustomField>
    <fullName>PrecoProduto__c</fullName>
    <label>Preço do Produto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProdutoController.cls
public with sharing class ProdutoController {
    @AuraEnabled(cacheable=true)
    public static List<Produto__c> buscarProdutos(){
        try {
            List<Produto__c> produtolista = [select id,Name,CodigoProduto__c,DescricaoProduto__c,PrecoProduto__c from Produto__c];
            return produtolista;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}